services:
  mariadb:
    image: 'mariadb:latest'
    restart: always
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    ports:
      - '3305:3306'
  redis:
    image: 'redis:latest'
    restart: always
    ports:
      - '6378:6379'
